name: bottom_sheet_scroll_wrapper
description: Just wrap the Scrollable Widget with the BottomSheetScrollWrapper so that dragging the bottom sheet works properly
version: 1.0.0
repository: https://github.com/Zotov-VD/bottom_sheet_scroll_wrapper

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
